 variable "worker_subnet_cidr_blocks" {}
 variable "control_plane_subnet_cidr_blocks" {}
 variable "availability_zones" {}
 variable "bastion_instance_type" {}
 variable "key_name" {}
 variable "load_balancer_https_cidr" {}
  variable "load_balancer_http_cidr" {}
 variable "region" {}
 variable "aws_profile" {}
 variable "bastion_ssh_cidr_blocks" {}
 variable "database_subnet_cidr_block" {}
 variable "load_balancer_subnet1_cidr_block" {}
 variable "load_balancer_subnet2_cidr_block" {}
 variable "bastion_subnet_cidr_block" {}
 variable "bastion_security_group_name" {}
 variable "vpc_cidr_block" {}
 variable "bastion_http_cidr_blocks" {}
 variable "bastion_https_cidr_blocks" {}
 variable "ami" {}
 variable "project_name" {}
 variable "worker_instance_type" {}
 variable "worker_node_count" {}
 variable "control_plane_instance_type" {}
 variable "control_plane_count" {}
 variable "worker-subnet-1" {}
 variable "worker-subnet-2" {}
 variable "control-plane-subnet-1" {}
 variable "control-plane-subnet-2" {}
 variable "vpc_id" {}
 

